#!/bin/bash
#using  pattern,to shift multiple characters.
#调用 create_pattern 获取转换模式，支持混合选项，读取标准输入直至EOF。
#get output from creat_pattern

pattern=$(./create_pattern "$@")
up=0
#IF -u found,
for arg in "$@"; do
    if [[ $arg = "-u" ]]; then
        up=1
    fi
done
#tr u or l through tr
if [ $up == 1 ]; then
    orig_set='[A-Z]'
else
    orig_set='[a-z]'
fi

#keep input untiil find"eof" or "EOF" 
while read input; 
do
    if [ $up == 0 ];then
        if [[ $input = "eof" ]]; then
            break
        fi
        #else no"eof"
        echo "$input" | tr '[a-z]' $pattern
    elif [ $up == 1 ]; then
        if [[ $input = "EOF" ]]; then
            break
        fi
        #if not EOF
        echo $input | tr '[A-Z]' $pattern
    fi
done
