#!/bin/bash
#ASSIGNMENT 1:"creating a pattern using in tr function as 2rd argument"

up=0 #no uppercase initialize
shift_num=0 #no shift-numbers initialize

#store all arguments in an array for future access? 
for arg in "$@"; 
do
#find whether have -u:
    if [[ $arg = "-u" ]];then
        up=1
    fi
done

#find if have -k 遍历参数查找 -k 后的移位数
i=1
for arg in "$@"; 
do
    i=$((i+1))
    if [[ $arg = "-k" ]];then
        # 使用参数展开方式获取 "-k" 后的参数值
        shift_num=${!i}
    fi
done

#display
chars=(a b c d e f g h i j k l m n o p q r s t u v w x y z)

#shift numbers
#if shift 26*n places ,it should remains the same as before
#数组下标从0开始，因此移位数为 2时，起始字母为数组中[2]（"c"），结束字母为[1]("b")
if [ $((shift_num % 26)) != 0 ];then
    pattern="[${chars[$shift_num]}-za-${chars[$((shift_num-1))]}]"
else
    pattern="[a-z]"
fi


#if have -u ,convert to upper case
if [ $up == 1 ];then
    pattern=${pattern^^}
fi
echo "$pattern"
