#!/bin/bash
#this code is to shift every line in a text file 25 times (shift from 1 to 25)
if [ $# -ne 1 ]; then
    echo "Usage: $0 filename"
    exit 1
fi

filename="$1"

for (( i = 1; i <= 25; i++ )); do
    echo "Shift $i"
    pattern=$(./create_pattern -k "$i" -u)
    cat "$filename" | tr '[A-Z]' "$pattern"
done
