#!/bin/bash
#shift every line in text file， 25 times ( shift 1-25)

for (( i = 1; i <= 25; i++ )); do
    echo "Shift $i"
    pattern=$(./create_pattern -k "$i" -u)
    cat "$filename" | tr '[A-Z]' $pattern
done

